pretrain: exps/k400/ViT-L/14/16f/k400-vit-l-14-f16.pt
resume:
seed: 1024
data:
    dataset: ucf101
    modality: RGB
    num_segments: 16
    seg_length: 1
    batch_size: 4
    workers: 4
    num_classes: 101
    image_tmpl: 'image_{:04d}.jpg'
    train_root: '/content/dataset/UCF-101-processed'
    val_root: '/content/dataset/UCF-101-processed'
    train_list: 'datasets/train_rgb_split_1.txt' 
    val_list: 'datasets/val_rgb_split_1.txt'
    label_list: 'datasets/labels.csv'
    input_size: 224
    random_shift: True
    output_path: exps
network:
    arch: ViT-L/14
    init: True
    tm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    sim_header: Transf
    interaction: VCS
    joint_st: False
    drop: 0      
    fix_text: True  
    fix_video: False
solver:
    type: cosine
    epochs: 20
    start_epoch: 0
    optim: adamw
    lr: 5.e-5
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: NCE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 2
